### ISSUE TITLE
Title row for playlists must be the same background color as Spotify, not transparent on themed clients

### ISSUE THREAD

**Issue by DroidZed** [JulienMaille/dribbblish-dynamic-theme#150]
**Is your feature request related to a problem? Please describe.**
When you scroll a playlist, the title bar that's sticky is transparent, making the texts in it unreadable.

**Describe the solution you'd like**
Adding a small CSS rule to the user.css file at the very end of the file to edit the class of that bar so it utilizes the bg color of the app.

```css
.main-trackList-trackList.main-trackList-indexable[aria-colcount="5"] 
.main-trackList-trackListRowGrid {
  background-color: var(--spice-main);
}
```

**Describe alternatives you've considered**
Adding that CSS part to the `Custom CSS` setting did the trick. But I guess if a lot of users liked the idea why not actually integrating it into the theme ?

**Additional context**

Here's a screenshot __before applying it__:

![image](https://user-images.githubusercontent.com/41507665/147774919-ed0fa57d-c0f4-4951-85a8-a29590377d3e.png)

And here's a screenshot after __applying it__:
![image](https://user-images.githubusercontent.com/41507665/147774994-54a5c67b-884a-41f1-ada9-f7e5166a8fe9.png)

In my opinion this looks way better than the default setting 💜

**Comment by JulienMaille** [comment]
Does it work in light theme too?

**Comment by DroidZed** [comment]
> Does it work in light theme too?

Yes :D

**Comment by DroidZed** [comment]
![image](https://user-images.githubusercontent.com/41507665/147819802-754c1b0c-0a63-4925-aecd-e1d1a012595a.png)

**Comment by DroidZed** [comment]
I guess it can be simplified to:

```css
.main-trackList-trackListRowGrid {
  background-color: var(--spice-main);
}
```
